### ISSUE TITLE
New FGUK version

### ISSUE THREAD

**Issue by JMaverick16** [FGMEMBERS/C-17#1]
Hi,
 could someone please update this repo so it has the latest FGUK changes, including the new livery pack available here: dl.dropboxusercontent.com/u/84179382/C17Liveries.zip (all files have to be replaced).
Thanks in advance.

**Comment by jan-hudec** [comment]
@JMaverick16, you are a member here, you should be able to do it yourself.

**Comment by JMaverick16** [comment]
How?
I can't use Git on my Mac as it is too old and I should upload all the 112MB from the web interface from scratch, without considering my low-bandwidth connection.

**Comment by FGDATA** [comment]
I find ssh transfers (via git) faster than http transfers (via web
interface). I haven't done serious reading or tests on the topic thou.
 :)

O.K -- I'll update the C17 today. Thanks for the note @JMaverick16

**Comment by FGDATA** [comment]
@JMaverick16 

I completed the update. This included

* Update fgukpayloads to compatible version 1.6
* Update C-17 to Version 3.1 and cherry-pick the small FGMEMBERS' fixes
* Add the Livery package you linked.

thanks for the Note, 

@IAHM-COL

**Comment by JMaverick16** [comment]
Thanks!
